<a href="https://colab.research.google.com/github/Bhoomika923/DATA_SCIENCE_NF/blob/main/Module2/classwork/Data_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#DATA MANIPULATION IN PANDAS

In [ ]:
import pandas as pd
L1 = [2,4,6,8,10]
var = pd.Series(L1)
print(var)
print(type(var))

0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
L1 = [2,4,6,8,10]
var = pd.Series(L1,index = ["a","b","c","d","e"]) #indexing as a b c d
print(var)

a     2
b     4
c     6
d     8
e    10
dtype: int64

In [ ]:
import pandas as pd
L1 = [2,4,6,8,10]
var = pd.Series(L1, index = ["a","b","c","d","e"], dtype = "float")
print(var)

a     2.0
b     4.0
c     6.0
d     8.0
e    10.0
dtype: float64

In [ ]:
import pandas as pd
L1 = [2,4,6,8,10]
var = pd.Series(L1, index = ["a","b","c","d","e"], dtype = "float", name = "myfile")
print(var)

a     2.0
b     4.0
c     6.0
d     8.0
e    10.0
Name: myfile, dtype: float64

In [ ]:
L1 = [1,2,3,4,5,7,8]
var2 = pd.Series(5,index= [1,2,3,4,5,6,7])
print(var2)

1    5
2    5
3    5
4    5
5    5
6    5
7    5
dtype: int64

In [ ]:
var2 = pd.Series(5,index= [2,7,9,13])
var3 = pd.Series(10,index= [1,5,9,11,13])
print(var2 + var3)

1      NaN
2      NaN
5      NaN
7      NaN
9     15.0
11     NaN
13    15.0
dtype: float64

In [ ]:
mydic= {
    "name" : ["A","A","C","D"],
    "roll no." : ["21","22","24","30"],
    "age" : ["22","19","25","18"],
}
var4 = pd.Series(mydic)
print(var4)

name            [A, A, C, D]
roll no.    [21, 22, 24, 30]
age         [22, 19, 25, 18]
dtype: object

In [ ]:
from numpy import mean
myseries= [2,3,4,5,6]
v= pd.Series(myseries)
Sum = v.sum()
print("sum of myseries","sum")
mean = v.mean()
print("mean of myseries","mean")

sum of myseries sum
mean of myseries mean

In [ ]:
list = [1,2,3,4]
ds = pd.Series(list)
#ds+5#
print(ds+5)

0    6
1    7
2    8
3    9
dtype: int64

In [ ]:
# DATAFRAMES

In [ ]:
import pandas as pd
L1 = [2,4,6,8,10]
df = pd.DataFrame(L1)
print(df)
print(type(df))

    0
0   2
1   4
2   6
3   8
4  10
<class 'pandas.core.frame.DataFrame'>

In [ ]:
info = {
    "name" : "Bhoomi",
    "age" : "21",
    "marks" : "90.5",
    "status" : True
}
df = pd.DataFrame(info,index = ["A","B","C"])
print(df)

     name age marks  status
A  Bhoomi  21  90.5    True
B  Bhoomi  21  90.5    True
C  Bhoomi  21  90.5    True

In [ ]:
import pandas as pd
info = {
    "name" : ["Bhoomi","riya","preeti","saurabh"],
    "age" : ["21","20","18","22"],
    "marks" : ["90.5","85.8","89.4","95.8"],
    "status" : [True,True,False,True]
}
df = pd.DataFrame(info,columns=["name","status","marks","status"])
print(df)

      name  status marks  status
0   Bhoomi    True  90.5    True
1     riya    True  85.8    True
2   preeti   False  89.4   False
3  saurabh    True  95.8    True

In [ ]:
info = {
    "name" : ["Bhoomi","riya","preeti","saurabh"],
    "age" : ["21","20","18","22"],
    "marks" : ["90.5","85.8","89.4","95.8"]
}
df = pd.DataFrame(info)
print(df["name"][3])

saurabh

In [ ]:
list1 = [['a','b','c','d'],['A','B','C','D']]
df=pd.DataFrame(list1)
print(df)

   0  1  2  3
0  a  b  c  d
1  A  B  C  D

In [ ]:
SR = {
"S":pd.Series([2,4,6,8]),
"R":pd.Series(["a","b","c","d"])
}
df=pd.DataFrame(SR)
#print(df)
df

   S  R
0  2  a
1  4  b
2  6  c
3  8  d

In [ ]:
df=pd.DataFrame({"A":[2,4,6,5],"B":[3,7,8,1]})
df["C"]= df["A"] + df["B"]
df

   A  B   C
0  2  3   5
1  4  7  11
2  6  8  14
3  5  1   6

In [ ]:
df=pd.DataFrame({"A":[2,4,6,5],"B":[3,7,8,1]})
df["C"]= df["A"] + df["B"]
df["try"]= df["A"]>4
df["try2"]= df["C"]<8
df

   A  B   C    try   try2
0  2  3   5  False   True
1  4  7  11  False  False
2  6  8  14   True  False
3  5  1   6   True   True

In [ ]:
import pandas as pd
df=pd.DataFrame({"A":[2,4,6,5]})
df.insert(1,'name',df['A'])
df.insert(2,'name2',["A","B","C","D"])
df

   A  name name2
0  2     2     A
1  4     4     B
2  6     6     C
3  5     5     D

In [ ]:
#MODULE 2  CHAPTER 2 - MERGE

In [ ]:
import pandas as pd
df1=pd.DataFrame({"A":[1,2,3,4],"B":['A','B','C','D']})
df2=pd.DataFrame({"A":[1,2,3,4],"D":['a','b','c','d']})
pd.merge(df1,df2)

   A  B  D
0  1  A  a
1  2  B  b
2  3  C  c
3  4  D  d

In [ ]:
import pandas as pd
df1=pd.DataFrame({"A":[1,2,3,4],"B":['A','B','C','D']})
df2=pd.DataFrame({"A":[1,2,3,4],"B":['a','b','c','d']})
pd.merge(df1,df2,on="B")

Empty DataFrame
Columns: [A_x, B, A_y]
Index: []

In [ ]:
import pandas as pd
df1=pd.DataFrame({"A":[1,2,3,4],"B":['A','B','C','D']})
df2=pd.DataFrame({"A":[1,5,3,7],"C":['a','b','c','d']})
pd.merge(df1,df2,on="A",how="inner",indicator='True')

   A  B  C  True
0  1  A  a  both
1  3  C  c  both

In [ ]:
import pandas as pd
df1=pd.DataFrame({"A":[1,2,3,4],"B":['A','B','C','D']})
df2=pd.DataFrame({"A":[1,5,3,7],"C":['a','b','c','d']})
pd.merge(df1,df2,on="A",how="outer",indicator='True')

   A    B    C        True
0  1    A    a        both
1  2    B  NaN   left_only
2  3    C    c        both
3  4    D  NaN   left_only
4  5  NaN    b  right_only
5  7  NaN    d  right_only

In [ ]:
import pandas as pd
df1=pd.DataFrame({"A":[1,2,3,4],"B":['A','B','C','D']})
df2=pd.DataFrame({"A":[1,5,3,7],"C":['a','b','c','d']})
pd.merge(df1,df2,on="A",how="left",indicator='True')

   A  B    C       True
0  1  A    a       both
1  2  B  NaN  left_only
2  3  C    c       both
3  4  D  NaN  left_only

In [ ]:
import pandas as pd
df1=pd.DataFrame({"A":[1,2,3,4],"B":['A','B','C','D']})
df2=pd.DataFrame({"A":[1,5,3,7],"C":['a','b','c','d']})
pd.merge(df1,df2,on="A",how="right",indicator='True')

   A    B  C        True
0  1    A  a        both
1  5  NaN  b  right_only
2  3    C  c        both
3  7  NaN  d  right_only

In [ ]:
import pandas as pd
df1=pd.DataFrame({"A":[1,2,3,4],"B":['A','B','C','D']})
df2=pd.DataFrame({"A":[1,2,3,4],"B":['a','b','c','d']})
pd.merge(df1,df2,left_index=True,right_index=True)

   A_x B_x  A_y B_y
0    1   A    1   a
1    2   B    2   b
2    3   C    3   c
3    4   D    4   d

In [ ]:
import pandas as pd
df1=pd.DataFrame({"A":[1,2,3,4],"B":['A','B','C','D']})
df2=pd.DataFrame({"A":[1,2,3,4],"B":['a','b','c','d']})
pd.merge(df1,df2,left_index=True,right_index=True,suffixes=('Id','name'))

   AId BId  Aname Bname
0    1   A      1     a
1    2   B      2     b
2    3   C      3     c
3    4   D      4     d

In [ ]:
import pandas as pd
df1=pd.DataFrame({"A":[1,2,3,4],"B":['A','B','C','D']})
df2=pd.DataFrame({"A":[1,2,3,4],"B":['a','b','c','d']})
pd.merge(df1,df2,left_index=True,right_index=True,suffixes=('_2004','_2005'))

   A_2004 B_2004  A_2005 B_2005
0       1      A       1      a
1       2      B       2      b
2       3      C       3      c
3       4      D       4      d